version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microting.eFormApi.BasePn
    versions:
    - 2.0.100
    - 2.0.101
    - 2.0.102
    - 2.0.103
    - 2.0.104
    - 2.0.106
    - 2.0.107
    - 2.0.108
    - 2.0.110
    - 2.0.111
    - 2.0.112
    - 2.0.113
    - 2.0.116
    - 2.0.117
    - 2.0.118
    - 2.0.122
    - 2.0.126
    - 2.0.127
    - 2.0.87
    - 2.0.88
    - 2.0.89
    - 2.0.90
    - 2.0.91
    - 2.0.93
    - 2.0.94
    - 2.0.95
    - 2.0.98
    - 2.0.99
    - 2.1.0
  - dependency-name: Microting.eForm
    versions:
    - 4.3.10
    - 4.3.11
    - 4.3.12
    - 4.3.14
    - 4.3.15
    - 4.3.16
    - 4.3.17
    - 4.3.18
    - 4.3.8
    - 4.3.9
    - 4.4.11
    - 4.4.13
    - 4.4.14
    - 4.4.17
    - 4.4.19
    - 4.4.2
    - 4.4.20
    - 4.4.22
    - 4.4.24
    - 4.4.26
    - 4.4.27
    - 4.4.3
    - 4.4.31
    - 4.4.35
    - 4.4.36
    - 4.4.4
    - 4.4.6
    - 4.4.7
    - 4.4.9
    - 4.5.0
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Relational
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
